// sprints.js
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const UPDATE_SPRINT = 'UPDATE_SPRINT';
export const ADD_SPRINT = 'ADD_SPRINT';
export const DELETE_SPRINT = 'DELETE_SPRINT';
export const ORDER_SPRINTS_BY_START_DATE = 'ORDER_SPRINTS_BY_START_DATE';
export const CLEAR_SPRINT_STORE = 'CLEAR_SPRINT_STORE';
export const LOAD_SPRINT_STORE = 'LOAD_SPRINT_STORE';
export const INITIALIZE_DEMO_DATA = 'INITIALIZE_DEMO_DATA';
export const MARK_SERVER_UPDATE_ERROR = 'MARK_SERVER_UPDATE_ERROR';

// authentication.js
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const INITIATE_DEMO_AUTH = 'INITIATE_DEMO_AUTH';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';