// sprints.js
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_SPRINT = 'UPDATE_SPRINT';
export const ADD_SPRINT = 'ADD_SPRINT';
export const ORDER_SPRINTS_BY_START_DATE = 'ORDER_SPRINTS_BY_START_DATE';