version: 2.1
orbs:
  node: circleci/node@1.1.6
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1
jobs:
  unit-tests:
    executor:
      name: node/default
    working_directory: /tmp/sprint-tracker
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - persist_to_workspace:
          root: .
          paths:
              - .
  build:
    executor:
      name: node/default
    working_directory: /tmp/sprint-tracker
    steps:
        - attach_workspace:
            at: .
        - run: npm run build
  deploy-job:
    docker:
      - image: circleci/node:10.16.3
    working_directory: /tmp/sprint-tracker
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
    build-and-test:
      jobs:
        - unit-tests
        - cypress/run: # "run" job comes from "cypress" orb
            start: npm start
            wait-on: 'http://localhost:3000'
        - build:
            requires:
              - unit-tests
              - cypress/run
        - deploy-job:
            requires:
              - build
            filters:
              branches:
                only: master